clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    tox:
        image: ${IMAGE}
        commands:
            - pip install tox
            - tox -e "${TOXENV}"
        volumes:
             - cache:/root/.cache

matrix:
    include:
        - IMAGE: tryton/tryton-test:3.5
          TOXENV: py35
        - IMAGE: tryton/tryton-test:3.6
          TOXENV: py36
        - IMAGE: tryton/tryton-test:3.7
          TOXENV: py37
        - IMAGE: tryton/tryton-test:3.8
          TOXENV: py38
